Various improvements to Gauss-Chebyshev equations
wavefunction91/IntegratorXX pull request #34
Opened 2023-07-08 09:33 UTC by susilehtola

Per @loriab comment in #27, 
- `gausscheby1` had a wrong equation in the code
- `gausscheby2` had a wrong equation in the comment
I also realized that I had an off-by-one error in `gausscheby3`.

This PR addresses these issues, and converts all `gausscheby` routines to use the same indexing. In my opinion, it is best to choose the indexing such that the equations match the mathematical expressions, since this makes checking their correctness easier.

2023-07-08 16:10 UTC, loriab commented
for abcissas for the third rule at https://github.com/wavefunction91/IntegratorXX/pull/27#issuecomment-1625193283 you have cos^2 whereas here in the code you have plain cos. Otherwise all three lgtm. I like the clearer indexing.

2023-07-08 16:14 UTC, wavefunction91 commented
+1 for the clearer indexing, but the bugs were fixed in #32. I'll address @susilehtola 's comments there and get that merged, and we can address the indexing with this PR

2023-07-08 18:38 UTC, wavefunction91 requested changes
As discussed, this should take #32 as its base. Also, while were on the topic of indexing, we should address the the problem of ascending vs descending ordering. It needs to be consistent. I know Psi4 does descending, but I'm not a huge fan of that for a number of reasons. I prefer to keep everything ascending to make life easier in the generation of pruned angular quadratures. For some quadratures, this can be done by simply swapping a sign of the point, for others its not so obvious. Probably best to just handle it by indexing redirection.

2023-07-08 19:16 UTC, loriab commented
I don't know if you're needing a comment for the Psi4 perspective, but I'm not following what ascending and descending refer to.

2023-07-08 20:38 UTC, wavefunction91 commented
@loriab As in having the quadratures stored in increasing (ascending) or decreasing (descending) order - [Psi4](https://github.com/psi4/psi4/blob/3439bbe86addee2c23eac8c06fc2870802115c9c/psi4/src/psi4/libfock/cubature.cc#L3686) assumes the latter, whereas I prefer to work with the former

The defaulting ordering is descending:
```
for(int i = 1; i < n; ++i) {
  auto xi = cos( M_PI * i / (n+1) ); // x[i] > x[i+1] for i in [0,n)
}
```
For GC-{1,2}, you can fix the order by just swapping the sign since the quadratures are symmetric. For GC-2-mod and GC-3, it's not so clear due to the change in variables.

2023-07-09 10:48 UTC, susilehtola commented
Rebased on top of #32. Indexing is now consistent, and all rules generate nodes in ascending order.

2023-07-09 17:44 UTC, wavefunction91 commented
@susilehtola Update with `master` (there's a minor conflict) and this is g2g.

2023-07-09 18:53 UTC, merged